### PR TITLE
add instance_container_name option

### PR DESCRIPTION
**Pull request by s-bernard**
Very similar to instance_host_name option, it is useful to have a deterministic container name.

### CODE REVIEW

**Comment by marcy-terui** [comment]
LGTM 👍 

But, I want to hear you about only one point. 
All names of containers must be unique on a host.
And, the instance names of test-kitchen are easy to duplicate.
Do you have any problem about this?

Thanks!

**Comment by s-bernard** [comment]
Well I don't see it to be a big problem. In my cookbooks, I usually have the cookbook name (or part of it) in suite names so instance names do not conflict between cookbooks.

**Comment by marcy-terui** [comment]
OK. I'll merge it. Thanks!

**Comment by marcy-terui** [comment]
Released as [0.16.0](https://rubygems.org/gems/kitchen-docker_cli/versions/0.16.0)

**Pull request merged**
