### PR TITLE
add option to pass filessystem path for 'docker build' context

### PR DESCRIPTION
**Pull request by nrvale0**

### CODE REVIEW

**Comment by nrvale0** [comment]
I can't seem to get the merge conflct to resolve but the changes are very minor. Perhaps it makes sense to just merge them manually on your end?

**Comment by marcy-terui** [comment]
@nrvale0 Sorry. On second thought, I decided to merge #23 
Because, I thought that it is better that we prepare a another option if we want it.

**Comment by marcy-terui** [comment]
I released `v0.14.1` that #23 is included.

Please check it.

**Comment by marcy-terui** [comment]
@nrvale0 Can I close this?

**Comment by nrvale0** [comment]
I agree with your previous assessment: this feature should wait until someone actually demonstrates a need. 

 :+1: 

Thanks for looking into it and merging the previous PR re build context. :)

**Pull request closed without merging**
